### ISSUE TITLE
version 0.0.8 fails to build with Ruby 2.2.0

### ISSUE THREAD

**Issue by alxklo** [louismullie/birch#11]
Attempting to install birch on MacOS 10.10.2 Yosemite using Ruby 2.2.0 preview 2, make fails. Using Ruby 2.1.1 installation completes successfully. Errors are as follows:

``` shell
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/alex/.rvm/rubies/ruby-2.2.0-preview2/bin/ruby -r ./siteconf20150310-16424-c2qgq7.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling native.c
native.c:39:8: warning: unused variable 'node_a' [-Wunused-variable]
        VALUE node_a;
              ^
native.c:40:8: warning: unused variable 'node_b' [-Wunused-variable]
        VALUE node_b;
              ^
native.c:41:8: warning: unused variable 'directed' [-Wunused-variable]
        VALUE directed;
              ^
native.c:42:8: warning: unused variable 'direction' [-Wunused-variable]
        VALUE direction;
              ^
native.c:58:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
native.c:272:8: warning: implicit declaration of function 'RHASH' is invalid in C99 [-Wimplicit-function-declaration]
  if (!RHASH(features)->ntbl) {
       ^
native.c:272:25: error: member reference type 'int' is not a pointer
  if (!RHASH(features)->ntbl) {
       ~~~~~~~~~~~~~~~  ^
6 warnings and 1 error generated.
make: *** [native.o] Error 1

make failed, exit code 2
```

**Comment by louismullie** [comment]
Seems to be due to this: https://bugs.ruby-lang.org/issues/9889 (RHASH has been hidden in 2.2)

**Comment by faustoct** [comment]
I implemented a patch for that. Check this out
https://github.com/faustoct/birch/blob/master/ext/birch/native.c

just adding:
#include <ruby/intern.h>

Is the first time that I'm using birch so I don't know how good is this fix
